# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  buildJarFile:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build docker image
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: 'biman20006@iiitd.ac.in'
          heroku_api_key: 'cf397d7d-6ab7-4f46-b63e-baeeacc96054'
          heroku_app_name: 'zenith-demo123'
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          process_type: web



